import { EVAL, INLINE, SELF, NONE, DATA, BLOB, CSPDirectives } from 'csp-header'

export type CSPPresetGenerator = (...args: any[]) => Partial<CSPDirectives>

export const cspConfig: CSPPresetGenerator = () => ({
  'default-src': [SELF],
  'connect-src': [SELF],
  'script-src': [SELF, INLINE, EVAL],
  'style-src': [SELF, INLINE],
  'img-src': [SELF, BLOB, DATA],
  'font-src': [SELF, DATA],
  'object-src': [NONE],
  'media-src': [SELF, BLOB, DATA],
  'frame-src': [SELF],
  'frame-ancestors': [SELF],
  'base-uri': [SELF],
  'form-action': [SELF],
})

export const recaptchaCspConfig: CSPPresetGenerator = () => ({
  'connect-src': ['https://www.google.com/recaptcha/'],
  'script-src': [
    'https://www.google.com/recaptcha/',
    'https://www.gstatic.com/recaptcha/',
  ],
  'frame-src': ['https://www.google.com/recaptcha/'],
})

export const googleTagManagerCspConfig: CSPPresetGenerator = () => ({
  'connect-src': [
    'www.googletagmanager.com',
    'www.google.com',
    'analytics.google.com',
    'https://analytics.google.com',
    'https://*.google-analytics.com',
    'https://*.analytics.google.com',
    'https://*.googletagmanager.com',
    'https://pagead2.googlesyndication.com',
    'https://www.googleadservices.com',
    'https://googleads.g.doubleclick.net',
    'https://google.com',
    'https://stats.g.doubleclick.net',
    'https://www.google.com',
    'https://www.google.ad',
    'https://www.google.ae',
    'https://www.google.com.af',
    'https://www.google.com.ag',
    'https://www.google.al',
    'https://www.google.am',
    'https://www.google.co.ao',
    'https://www.google.com.ar',
    'https://www.google.as',
    'https://www.google.at',
    'https://www.google.com.au',
    'https://www.google.az',
    'https://www.google.ba',
    'https://www.google.com.bd',
    'https://www.google.be',
    'https://www.google.bf',
    'https://www.google.bg',
    'https://www.google.com.bh',
    'https://www.google.bi',
    'https://www.google.bj',
    'https://www.google.com.bn',
    'https://www.google.com.bo',
    'https://www.google.com.br',
    'https://www.google.bs',
    'https://www.google.bt',
    'https://www.google.co.bw',
    'https://www.google.by',
    'https://www.google.com.bz',
    'https://www.google.ca',
    'https://www.google.cd',
    'https://www.google.cf',
    'https://www.google.cg',
    'https://www.google.ch',
    'https://www.google.ci',
    'https://www.google.co.ck',
    'https://www.google.cl',
    'https://www.google.cm',
    'https://www.google.cn',
    'https://www.google.com.co',
    'https://www.google.co.cr',
    'https://www.google.com.cu',
    'https://www.google.cv',
    'https://www.google.com.cy',
    'https://www.google.cz',
    'https://www.google.de',
    'https://www.google.dj',
    'https://www.google.dk',
    'https://www.google.dm',
    'https://www.google.com.do',
    'https://www.google.dz',
    'https://www.google.com.ec',
    'https://www.google.ee',
    'https://www.google.com.eg',
    'https://www.google.es',
    'https://www.google.com.et',
    'https://www.google.fi',
    'https://www.google.com.fj',
    'https://www.google.fm',
    'https://www.google.fr',
    'https://www.google.ga',
    'https://www.google.ge',
    'https://www.google.gg',
    'https://www.google.com.gh',
    'https://www.google.com.gi',
    'https://www.google.gl',
    'https://www.google.gm',
    'https://www.google.gr',
    'https://www.google.com.gt',
    'https://www.google.gy',
    'https://www.google.com.hk',
    'https://www.google.hn',
    'https://www.google.hr',
    'https://www.google.ht',
    'https://www.google.hu',
    'https://www.google.co.id',
    'https://www.google.ie',
    'https://www.google.co.il',
    'https://www.google.im',
    'https://www.google.co.in',
    'https://www.google.iq',
    'https://www.google.is',
    'https://www.google.it',
    'https://www.google.je',
    'https://www.google.com.jm',
    'https://www.google.jo',
    'https://www.google.co.jp',
    'https://www.google.co.ke',
    'https://www.google.com.kh',
    'https://www.google.ki',
    'https://www.google.kg',
    'https://www.google.co.kr',
    'https://www.google.com.kw',
    'https://www.google.kz',
    'https://www.google.la',
    'https://www.google.com.lb',
    'https://www.google.li',
    'https://www.google.lk',
    'https://www.google.co.ls',
    'https://www.google.lt',
    'https://www.google.lu',
    'https://www.google.lv',
    'https://www.google.com.ly',
    'https://www.google.co.ma',
    'https://www.google.md',
    'https://www.google.me',
    'https://www.google.mg',
    'https://www.google.mk',
    'https://www.google.ml',
    'https://www.google.com.mm',
    'https://www.google.mn',
    'https://www.google.com.mt',
    'https://www.google.mu',
    'https://www.google.mv',
    'https://www.google.mw',
    'https://www.google.com.mx',
    'https://www.google.com.my',
    'https://www.google.co.mz',
    'https://www.google.com.na',
    'https://www.google.com.ng',
    'https://www.google.com.ni',
    'https://www.google.ne',
    'https://www.google.nl',
    'https://www.google.no',
    'https://www.google.com.np',
    'https://www.google.nr',
    'https://www.google.nu',
    'https://www.google.co.nz',
    'https://www.google.com.om',
    'https://www.google.com.pa',
    'https://www.google.com.pe',
    'https://www.google.com.pg',
    'https://www.google.com.ph',
    'https://www.google.com.pk',
    'https://www.google.pl',
    'https://www.google.pn',
    'https://www.google.com.pr',
    'https://www.google.ps',
    'https://www.google.pt',
    'https://www.google.com.py',
    'https://www.google.com.qa',
    'https://www.google.ro',
    'https://www.google.ru',
    'https://www.google.rw',
    'https://www.google.com.sa',
    'https://www.google.com.sb',
    'https://www.google.sc',
    'https://www.google.se',
    'https://www.google.com.sg',
    'https://www.google.sh',
    'https://www.google.si',
    'https://www.google.sk',
    'https://www.google.com.sl',
    'https://www.google.sn',
    'https://www.google.so',
    'https://www.google.sm',
    'https://www.google.sr',
    'https://www.google.st',
    'https://www.google.com.sv',
    'https://www.google.td',
    'https://www.google.tg',
    'https://www.google.co.th',
    'https://www.google.com.tj',
    'https://www.google.tl',
    'https://www.google.tm',
    'https://www.google.tn',
    'https://www.google.to',
    'https://www.google.com.tr',
    'https://www.google.tt',
    'https://www.google.com.tw',
    'https://www.google.co.tz',
    'https://www.google.com.ua',
    'https://www.google.co.ug',
    'https://www.google.co.uk',
    'https://www.google.com.uy',
    'https://www.google.co.uz',
    'https://www.google.com.vc',
    'https://www.google.co.ve',
    'https://www.google.co.vi',
    'https://www.google.com.vn',
    'https://www.google.vu',
    'https://www.google.ws',
    'https://www.google.rs',
    'https://www.google.co.za',
    'https://www.google.co.zm',
    'https://www.google.co.zw',
    'https://www.google.cat',
  ],
  'script-src': [
    'https://www.googletagmanager.com',
    'https://googletagmanager.com',
    'https://tagmanager.google.com',
    'https://*.googletagmanager.com',
    'https://www.googleadservices.com',
    'https://www.google.com',
    'https://pagead2.googlesyndication.com',
    'https://googleads.g.doubleclick.net',
  ],
  'frame-src': ['https://www.googletagmanager.com'],
  'img-src': [
    'www.googletagmanager.com',
    'https://googletagmanager.com',
    'https://ssl.gstatic.com',
    'https://www.gstatic.com',
    'https://*.google-analytics.com',
    'https://*.googletagmanager.com',
    'https://www.googletagmanager.com',
    'https://googleads.g.doubleclick.net',
    'https://www.google.com',
    'https://pagead2.googlesyndication.com',
    'https://www.googleadservices.com',
    'https://google.com',
    'https://www.google.com',
    'https://www.google.ad',
    'https://www.google.ae',
    'https://www.google.com.af',
    'https://www.google.com.ag',
    'https://www.google.al',
    'https://www.google.am',
    'https://www.google.co.ao',
    'https://www.google.com.ar',
    'https://www.google.as',
    'https://www.google.at',
    'https://www.google.com.au',
    'https://www.google.az',
    'https://www.google.ba',
    'https://www.google.com.bd',
    'https://www.google.be',
    'https://www.google.bf',
    'https://www.google.bg',
    'https://www.google.com.bh',
    'https://www.google.bi',
    'https://www.google.bj',
    'https://www.google.com.bn',
    'https://www.google.com.bo',
    'https://www.google.com.br',
    'https://www.google.bs',
    'https://www.google.bt',
    'https://www.google.co.bw',
    'https://www.google.by',
    'https://www.google.com.bz',
    'https://www.google.ca',
    'https://www.google.cd',
    'https://www.google.cf',
    'https://www.google.cg',
    'https://www.google.ch',
    'https://www.google.ci',
    'https://www.google.co.ck',
    'https://www.google.cl',
    'https://www.google.cm',
    'https://www.google.cn',
    'https://www.google.com.co',
    'https://www.google.co.cr',
    'https://www.google.com.cu',
    'https://www.google.cv',
    'https://www.google.com.cy',
    'https://www.google.cz',
    'https://www.google.de',
    'https://www.google.dj',
    'https://www.google.dk',
    'https://www.google.dm',
    'https://www.google.com.do',
    'https://www.google.dz',
    'https://www.google.com.ec',
    'https://www.google.ee',
    'https://www.google.com.eg',
    'https://www.google.es',
    'https://www.google.com.et',
    'https://www.google.fi',
    'https://www.google.com.fj',
    'https://www.google.fm',
    'https://www.google.fr',
    'https://www.google.ga',
    'https://www.google.ge',
    'https://www.google.gg',
    'https://www.google.com.gh',
    'https://www.google.com.gi',
    'https://www.google.gl',
    'https://www.google.gm',
    'https://www.google.gr',
    'https://www.google.com.gt',
    'https://www.google.gy',
    'https://www.google.com.hk',
    'https://www.google.hn',
    'https://www.google.hr',
    'https://www.google.ht',
    'https://www.google.hu',
    'https://www.google.co.id',
    'https://www.google.ie',
    'https://www.google.co.il',
    'https://www.google.im',
    'https://www.google.co.in',
    'https://www.google.iq',
    'https://www.google.is',
    'https://www.google.it',
    'https://www.google.je',
    'https://www.google.com.jm',
    'https://www.google.jo',
    'https://www.google.co.jp',
    'https://www.google.co.ke',
    'https://www.google.com.kh',
    'https://www.google.ki',
    'https://www.google.kg',
    'https://www.google.co.kr',
    'https://www.google.com.kw',
    'https://www.google.kz',
    'https://www.google.la',
    'https://www.google.com.lb',
    'https://www.google.li',
    'https://www.google.lk',
    'https://www.google.co.ls',
    'https://www.google.lt',
    'https://www.google.lu',
    'https://www.google.lv',
    'https://www.google.com.ly',
    'https://www.google.co.ma',
    'https://www.google.md',
    'https://www.google.me',
    'https://www.google.mg',
    'https://www.google.mk',
    'https://www.google.ml',
    'https://www.google.com.mm',
    'https://www.google.mn',
    'https://www.google.com.mt',
    'https://www.google.mu',
    'https://www.google.mv',
    'https://www.google.mw',
    'https://www.google.com.mx',
    'https://www.google.com.my',
    'https://www.google.co.mz',
    'https://www.google.com.na',
    'https://www.google.com.ng',
    'https://www.google.com.ni',
    'https://www.google.ne',
    'https://www.google.nl',
    'https://www.google.no',
    'https://www.google.com.np',
    'https://www.google.nr',
    'https://www.google.nu',
    'https://www.google.co.nz',
    'https://www.google.com.om',
    'https://www.google.com.pa',
    'https://www.google.com.pe',
    'https://www.google.com.pg',
    'https://www.google.com.ph',
    'https://www.google.com.pk',
    'https://www.google.pl',
    'https://www.google.pn',
    'https://www.google.com.pr',
    'https://www.google.ps',
    'https://www.google.pt',
    'https://www.google.com.py',
    'https://www.google.com.qa',
    'https://www.google.ro',
    'https://www.google.ru',
    'https://www.google.rw',
    'https://www.google.com.sa',
    'https://www.google.com.sb',
    'https://www.google.sc',
    'https://www.google.se',
    'https://www.google.com.sg',
    'https://www.google.sh',
    'https://www.google.si',
    'https://www.google.sk',
    'https://www.google.com.sl',
    'https://www.google.sn',
    'https://www.google.so',
    'https://www.google.sm',
    'https://www.google.sr',
    'https://www.google.st',
    'https://www.google.com.sv',
    'https://www.google.td',
    'https://www.google.tg',
    'https://www.google.co.th',
    'https://www.google.com.tj',
    'https://www.google.tl',
    'https://www.google.tm',
    'https://www.google.tn',
    'https://www.google.to',
    'https://www.google.com.tr',
    'https://www.google.tt',
    'https://www.google.com.tw',
    'https://www.google.co.tz',
    'https://www.google.com.ua',
    'https://www.google.co.ug',
    'https://www.google.co.uk',
    'https://www.google.com.uy',
    'https://www.google.co.uz',
    'https://www.google.com.vc',
    'https://www.google.co.ve',
    'https://www.google.co.vi',
    'https://www.google.com.vn',
    'https://www.google.vu',
    'https://www.google.ws',
    'https://www.google.rs',
    'https://www.google.co.za',
    'https://www.google.co.zm',
    'https://www.google.co.zw',
    'https://www.google.cat',
  ],
  'style-src': [
    'https://googletagmanager.com',
    'https://tagmanager.google.com',
    'https://fonts.googleapis.com',
  ],
  'font-src': ['https://fonts.gstatic.com'],
})

export const facebookPixelCspConfig: CSPPresetGenerator = () => ({
  'script-src': ['https://connect.facebook.net'],
  'img-src': ['https://www.facebook.com'],
  'connect-src': ['https://www.facebook.com'],
})

export const typekitCspConfig: CSPPresetGenerator = () => ({
  'script-src': ['use.typekit.net'],
  'style-src': ['use.typekit.net'],
  'font-src': ['use.typekit.net'],
  'img-src': ['p.typekit.net'],
  'connect-src': ['performance.typekit.net'],
})

export const cloudflareCspConfig: CSPPresetGenerator = () => ({
  'script-src': [
    SELF,
    INLINE,
    'ajax.cloudflare.com',
    'static.cloudflareinsights.com',
    'https://challenges.cloudflare.com',
  ],
  'connect-src': ['cloudflareinsights.com'],
  'frame-src': ['https://challenges.cloudflare.com'],
})

export const googleMapsCspConfig: CSPPresetGenerator = () => ({
  'script-src': ['https://maps.googleapis.com'],
  'connect-src': ['https://maps.googleapis.com'],
  'img-src': ['https://maps.googleapis.com', 'https://maps.gstatic.com'],
})
